title: Stuff and Things
description: Worth writing down? Sure. Remembering? Maybe.
remote_theme: pages-themes/midnight@v0.2.0
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
date_format: "%b %-d, %Y"
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

